# Estudos com NumPy

## Importando

In [1]:
import numpy as np

## Criando estruturas de dados

In [2]:
# criando uma estrutura unidimensional
array1 = np.array([1,2,3,4,5])

In [3]:
array1

array([1, 2, 3, 4, 5])

In [8]:
# criando uma estrutura bi-dimensional
array2 = np.array([[1,2,3], [4,5,6]])

In [9]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

## verificando o tamanho do objeto

In [11]:
# verificando o formato do array
array2.shape

(2, 3)

In [15]:
# verificando as dimensões
array2.ndim

2

## Função Arange:
Semelhante ao range do python, retorna uma sequencia de valores:<br>
np.arange(start, end, step)

In [20]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Função linspace
Retorna uma sequência <br > np.linspace(start, end, quantidade)

In [24]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

## Criar varios tipos diferentes de matrizes

In [28]:
# matriz com 0
# para mais dimensões passar uma tupla
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
# Matriz preenchida com 1
# para mais dimensões passar uma tupla
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
# Matriz identidade
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
# Matriz com valores da diagonal pré-definidos
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [59]:
# Matriz transposta (pivot)
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
a.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [60]:
# ou a função transpose
np.transpose(a)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

## Slicing
A indexação começa em 0

In [33]:
a = np.arange(20)

In [35]:
# 4 valor
a[3]

3

In [37]:
# 10 primeiros
a[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [40]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
# valor 7
a[1][2]

7

In [44]:
# primeira linha
a[0]

array([1, 2, 3, 4])

In [47]:
# outra forma
a[1,2]

7

In [49]:
# é possivel usar a anotação de : e separar a linha e a coluna por ,
# segunda coluna
a[:,1]

array([2, 6])

In [52]:
# duas ultimas colunas
a[:,2:]

array([[3, 4],
       [7, 8]])

## Reshape
## Função ravel
Ela retira as dimensões dos dados e deixa eles em formato de um array unidimensional

In [62]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## função reshape
ela altera as dimensões do objeto

In [64]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [66]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Função sort
Ordena um array

In [73]:
a = np.array([[3,1,2],[4,6,5]])

In [70]:
a

array([[3, 1, 2],
       [4, 6, 5]])

In [74]:
# ordenar por linha
a.sort(axis=1)

In [76]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
a = np.array([[5,3,2,7],[1,3,9,5]])

In [81]:
a

array([[5, 3, 2, 7],
       [1, 3, 9, 5]])

In [83]:
# ordenar por coluna
a.sort(axis=0)

In [84]:
a

array([[1, 3, 2, 5],
       [5, 3, 9, 7]])